### ISSUE TITLE
运行程序后报错了,怎么解决啊,没改过代码

### ISSUE THREAD

**Issue by ddt2016** [Jiahonzheng/JGM-Automator#2]
Traceback (most recent call last):
  File "...\JGM-Automator-master\main.py", line 19, in <module>
    instance.start()
  File "..\JGM-Automator-master\automator.py", line 21, in start
    self._match_target(target)
  File "..\JGM-Automator-master\automator.py", line 69, in _match_target
    screen = self.d.screenshot(format="opencv")
  File "..\Python37\lib\site-packages\uiautomator2\__init__.py", line 1186, in screenshot
    return self.session().screenshot(*args, **kwargs)
  File "<..\Python37\lib\site-packages\decorator.py:decorator-gen-6>", line 2, in screenshot
  File "..\Python37\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "..\Python37\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "..\Python37\lib\site-packages\uiautomator2\session.py", line 482, in screenshot
    return cv2.imdecode(nparr, cv2.IMREAD_COLOR)
cv2.error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:726: error: (-215:Assertion failed) !buf.empty() in function 'cv::imdecode_'

**Comment by ddt2016** [comment]
额,查了一下,把地址填完整就可以了
