### ISSUE TITLE
NoneType报错，运行main.py后直接出现的这个

### ISSUE THREAD

**Issue by qq4199** [Jiahonzheng/JGM-Automator#29]
C:\Python3.7.4\python.exe D:/game/JGM/qingwei/main.py
Successfully connected to MuMu.
1080 1920
App is front. JGM agent start in 5 seconds
Traceback (most recent call last):
  File "D:/game/JGM/qingwei/main.py", line 25, in <module>
    instance.start()
  File "D:\game\JGM\qingwei\automator.py", line 44, in start
    self.check_task()
  File "D:\game\JGM\qingwei\automator.py", line 168, in check_task
    if UIMatcher.findTaskBubble(screen):
  File "D:\game\JGM\qingwei\cv.py", line 70, in findTaskBubble
    if len(cnts[1]):
TypeError: object of type 'NoneType' has no len()

**Comment by TsingWei** [comment]
在这里已经修复了 https://github.com/TsingWei/Simple-JiaGuoMeng-Agent

**Comment by TsingWei** [comment]
好了这回真的修复了 https://github.com/TsingWei/Simple-JiaGuoMeng-Agent

**Comment by bluecc88** [comment]
> 好了这回真的修复了 https://github.com/TsingWei/Simple-JiaGuoMeng-Agent

是的，好了
