### ISSUE TITLE
启动main.py时报错是怎么回事呢？

### ISSUE THREAD

**Issue by lqxandxl** [Jiahonzheng/JGM-Automator#3]
需要手机吗？还是只有电脑就行。
(python37) C:\Users\Administrator\Desktop\JGM-Automator-master>python main.py
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    instance = Automator('localhost:7555', targets)
  File "C:\Users\Administrator\Desktop\JGM-Automator-master\automator.py", line 11, in __init__
    self.d = u2.connect(device)
  File "C:\ProgramData\Anaconda3\envs\python37\lib\site-packages\uiautomator2\__init__.py", line 122, in connect
    return connect_usb(addr)
  File "C:\ProgramData\Anaconda3\envs\python37\lib\site-packages\uiautomator2\__init__.py", line 164, in connect_usb
    lport = device.forward_port(7912)
  File "C:\ProgramData\Anaconda3\envs\python37\lib\site-packages\adbutils\__init__.py", line 383, in forward_port
    for f in self.forward_list():
  File "C:\ProgramData\Anaconda3\envs\python37\lib\site-packages\adbutils\__init__.py", line 224, in forward_list
    c.check_okay()
  File "C:\ProgramData\Anaconda3\envs\python37\lib\site-packages\adbutils\__init__.py", line 137, in check_okay
    raise AdbError(self.read_string())
adbutils.errors.AdbError: unknown host service

**Comment by Jiahonzheng** [comment]
可以不需要手机。在MuMu模拟器开启的情况下，打开 USB 调试模式，最好将 localhost:7555 改成 127.0.0.1:7555 因为也有可能这个 UIAutomator2 在解析上可能会抽风。

**Comment by gityfx2018** [comment]
C:\python3\Python36\python36.exe G:/google_download/yfx/vscode/yufx/JGM-rapid-automator-master/main.py
火车来了！
Traceback (most recent call last):
  File "G:/google_download/yfx/vscode/yufx/JGM-rapid-automator-master/main.py", line 42, in <module>
    instance.start()
  File "G:\google_download\yfx\vscode\yufx\JGM-rapid-automator-master\automator.py", line 46, in start
    if self._match_target(target,screen):
  File "G:\google_download\yfx\vscode\yufx\JGM-rapid-automator-master\automator.py", line 76, in _match_target
    result = UIMatcher.match(screen, target)
  File "G:\google_download\yfx\vscode\yufx\JGM-rapid-automator-master\cv.py", line 15, in match
    th, tw = template.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
正在寻找001


这是什么错啊。。

**Comment by Jiahonzheng** [comment]
估计是对应的货物的图片缺失。

**Comment by Aratoki** [comment]
C:\Users\Arato\Desktop\JGM-Automator-master(1)\JGM-Automator-master>python main.py
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    instance = Automator('3204539b871a2181', targets)
  File "C:\Users\Arato\Desktop\JGM-Automator-master(1)\JGM-Automator-master\automator.py", line 19, in __init__
    self.d = u2.connect(device)
  File "C:\Python\Python37-32\lib\site-packages\uiautomator2\__init__.py", line 122, in connect
    return connect_usb(addr)
  File "C:\Python\Python37-32\lib\site-packages\uiautomator2\__init__.py", line 164, in connect_usb
    lport = device.forward_port(7912)
  File "C:\Python\Python37-32\lib\site-packages\adbutils\__init__.py", line 388, in forward_port
    self._client.forward(self._serial, "tcp:" + str(local_port), remote)
  File "C:\Python\Python37-32\lib\site-packages\adbutils\__init__.py", line 250, in forward
    c.check_okay()
  File "C:\Python\Python37-32\lib\site-packages\adbutils\__init__.py", line 137, in check_okay
    raise AdbError(self.read_string())
adbutils.errors.AdbError

大佬这是为啥啊

**Comment by Xtimeshadow** [comment]
D:\JGM-Automator-master>python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from automator import Automator
  File "D:\JGM-Automator-master\automator.py", line 2, in <module>
    from cv import UIMatcher
  File "D:\JGM-Automator-master\cv.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

大佬这是什么原因啊？

**Comment by TsingWei** [comment]
你本机没装opencv-python可能
