### ISSUE TITLE
RuntimeError: atx-agent recover failed报错

### ISSUE THREAD

**Issue by murphyzhu0823** [Jiahonzheng/JGM-Automator#30]
按照教程一步一步走，最后在main.py执行的时候报这个错
PS D:\JGM-Automator> python.exe .\main.py
Successfully connected to MuMu.
C:\Program Files\Python37\lib\site-packages\uiautomator2\__init__.py:177: RuntimeWarning: start atx-agent ...
  warnings.warn("start atx-agent ...", RuntimeWarning)
Traceback (most recent call last):
  File ".\main.py", line 23, in <module>
    instance = Automator(MuMu, up_list, harvest_filter,auto_policy=policy,auto_task=task,speedup=speed_up)
  File "D:\JGM-Automator\automator.py", line 14, in __init__
    self.d = u2.connect(device)
  File "C:\Program Files\Python37\lib\site-packages\uiautomator2\__init__.py", line 122, in connect
    return connect_usb(addr)
  File "C:\Program Files\Python37\lib\site-packages\uiautomator2\__init__.py", line 186, in connect_usb
    raise RuntimeError("atx-agent recover failed")
RuntimeError: atx-agent recover failed

使用的是Mumu模拟器

**Comment by TsingWei** [comment]
你看mumu里面小黄车安装成功没

**Comment by murphyzhu0823** [comment]
看了下是本地开了酸酸乳代理。。。
