### ISSUE TITLE
运行main.py时出错，使用的是手机

### ISSUE THREAD

**Issue by YangyuCH** [Jiahonzheng/JGM-Automator#32]
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    if b'connected' in subprocess.check_output('adb connect '+ MuMu):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'adb connect 127.0.0.1:7555': 'adb connect 127.0.0.1:7555'

**Comment by TsingWei** [comment]
应该还没装adb, 可以把项目目录下的`adb`文件夹添加到环境变量path里面

**Comment by YangyuCH** [comment]
安装了adb ，使用adb devices也正常

**Comment by TsingWei** [comment]
那把这里21行到22行注释掉试试
https://github.com/Jiahonzheng/JGM-Automator/blob/c8a1fef175a30dba7932fedcaeeefeb6ab5528d6/main.py#L21-L22
这里相当于代替你执行了一遍adb connect

**Comment by YangyuCH** [comment]
谢谢你，注释后没没这个问题了

 raise err
uiautomator2.exceptions.JsonRpcError: -32001 Jsonrpc error: <java.lang.SecurityException> data: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.IUiAutomationConnection$Stub$Proxy.injectInputEvent(IUiAutomationConnection.java:292)
	at android.app.UiAutomation.injectInputEvent(UiAutomation.java:516)
	at android.support.test.uiautomator.InteractionController.injectEventSync(InteractionController.java:690)
	at android.support.test.uiautomator.InteractionController.touchDown(InteractionController.java:351)
	at android.support.test.uiautomator.InteractionController.clickNoSync(InteractionController.java:220)
	at android.support.test.uiautomator.UiDevice.click(UiDevice.java:557)
	at com.github.uiautomator.stub.AutomatorServiceImpl.click(AutomatorServiceImpl.java:179)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:467)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:352)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:283)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:251)
	at com.github.uiautomator.stub.AutomatorHttpServer.serve(AutomatorHttpServer.java:100)
	at fi.iki.elonen.NanoHTTPD.serve(NanoHTTPD.java:2244)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:764)
, method: click
