### ISSUE TITLE
自动升级政策时候出错

### ISSUE THREAD

**Issue by fengyong2015** [Jiahonzheng/JGM-Automator#36]
```
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    instance.start()
  File "/Users/xxxxxxxx/work/git_private/JGM-Automator/automator.py", line 42, in start
    self.check_policy()
  File "/Users/xxxxxxxx/work/git_private/JGM-Automator/automator.py", line 138, in check_policy
    if len(UIMatcher.findGreenArrow(self.d.screenshot(format="opencv"))):
  File "/Users/xxxxxxxx/work/git_private/JGM-Automator/cv.py", line 31, in findGreenArrow
    if cnts[1]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by TsingWei** [comment]
已修复, 请重新pull, 而且为了保险起见换用openCV3.x版本 @fengyong2015
