### ISSUE TITLE
政策中心升级的时候程序报错退出

### ISSUE THREAD

**Issue by ansemz** [Jiahonzheng/JGM-Automator#45]
Traceback (most recent call last):                                                                                                                                                           
  File "main.py", line 25, in <module>                                                                                                                                                       
    instance.start()                                                                                                                                                                         
  File "/mnt/d/Downloads/JGM-Automator/automator.py", line 42, in start                                                                                                                      
    self.check_policy()                                                                                                                                                                      
  File "/mnt/d/Downloads/JGM-Automator/automator.py", line 142, in check_policy                                                                                                              
    if len(UIMatcher.findGreenArrow(self.d.screenshot(format="opencv"))):                                                                                                                    
  File "/mnt/d/Downloads/JGM-Automator/cv.py", line 36, in findGreenArrow                                                                                                                    
    cX = int(M["m10"] / M["m00"])                                                                                                                                                            
ZeroDivisionError: float division by zero

**Comment by jslyxyc** [comment]
openCV版本差异问题：
  openCV2和openCV4中，findContours这个轮廓提取函数会返回两个值：
    ①轮廓的点集(contours)
    ②各层轮廓的索引(hierarchy)
  openCV3中，则会返回三个值：
    ①处理的图像(image)
    ②轮廓的点集(contours)
    ③各层轮廓的索引(hierarchy)

更新代码、更新依赖即可：
  python -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
