### ISSUE TITLE
你好，我这出了一个奇怪的错误

### ISSUE THREAD

**Issue by 174639357** [Jiahonzheng/JGM-Automator#62]
Traceback (most recent call last):
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
            (self._dns_host, self.port), self.timeout, **extra_kw
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
    ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 966, in send
    self.connect()
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 184, in connect
    conn = self._new_conn()
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
    urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10AF1C90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 762, in urlopen
    **response_kw
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 762, in urlopen
    **response_kw
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 762, in urlopen
    **response_kw
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=63812): Max retries exceeded with url: /info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10AF1C90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "huawei.py", line 27, in <module>
    instance.start()
    File "C:\Users\xxx\Desktop\JGM-Automator-master\automator.py", line 51, in start
    self.d.click(550/1080, 1650/1920)
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator2\session.py", line 364, in click
    x, y = self.pos_rel2abs(x, y)
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator2\session.py", line 155, in convert
    self.server.window_size())  # size will be [width, height]
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator2\__init__.py", line 396, in window_size
    info = self._reqsess.get(self.path2url('/info')).json()
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\uiautomator2\__init__.py", line 245, in request
    self).request(method, url, **kwargs)
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
    File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=63812): Max retries exceeded with url: /info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10AF1C90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

**Comment by TsingWei** [comment]
使用wifi连接试试
