### ISSUE TITLE
 python -m uiautomator2 init之后出错

### ISSUE THREAD

**Issue by Clark3333** [Jiahonzheng/JGM-Automator#66]
atx软件可以安装但是报错
[D 191105 22:12:39 init:109] Initial device AdbDevice(serial=127.0.0.1:7555)
[I 191105 22:12:39 init:277] Install minicap, minitouch
[D 191105 22:12:39 init:48] Use cached assets: C:\Users\User\.uiautomator2\383030fa57087cbc4edca315ef01dac9fe671d3304263fb5f6016c6c\minitouch
[D 191105 22:12:39 init:186] Push to /data/local/tmp/minitouch:0755
[I 191105 22:12:39 init:281] abi:x86 seems to be android emulator, skip install minicap
[D 191105 22:12:39 init:48] Use cached assets: C:\Users\User\.uiautomator2\6edef50a02af79ddf2217874d1ce621d4a847d6762dc86c10d5811a0\bundle.jar
[D 191105 22:12:39 init:186] Push to /data/local/tmp/bundle.jar:0644
[D 191105 22:12:40 init:48] Use cached assets: C:\Users\User\.uiautomator2\42a21461fa2b0031646c206175ef315ae8a142421a7675e219336bca\uiautomator-stub.jar
[D 191105 22:12:40 init:186] Push to /data/local/tmp/uiautomator-stub.jar:0644
[I 191105 22:12:40 init:295] Already installed com.github.uiautomator apks
[D 191105 22:12:40 init:214] Real version: [0, 7, 4], Expect version: [0, 7, 4]
[I 191105 22:12:40 init:300] Check install
[D 191105 22:12:40 init:310] Forward: local:tcp:12388 -> remote:tcp:7912
[D 191105 22:12:40 init:310] Forward: local:tcp:12388 -> remote:tcp:7912
[D 191105 22:12:41 init:310] Forward: local:tcp:12388 -> remote:tcp:7912
[D 191105 22:12:41 init:310] Forward: local:tcp:12388 -> remote:tcp:7912
[D 191105 22:12:42 init:310] Forward: local:tcp:12388 -> remote:tcp:7912
[D 191105 22:12:42 init:310] Forward: local:tcp:12388 -> remote:tcp:7912
[D 191105 22:12:43 init:310] Forward: local:tcp:12388 -> remote:tcp:7912
[D 191105 22:12:43 init:310] Forward: local:tcp:12388 -> remote:tcp:7912
[D 191105 22:12:44 init:310] Forward: local:tcp:12388 -> remote:tcp:7912
[D 191105 22:12:44 init:310] Forward: local:tcp:12388 -> remote:tcp:7912
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1336, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1336, in getresponse
    response.begin()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 229, in <module>
    main()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 219, in main
    actions[args.subparser](args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__main__.py", line 34, in cmd_init
    init.install(args.server)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\init.py", line 301, in install
    self.check_atx_agent_version()
  File "<C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\decorator.py:decorator-gen-4>", line 2, in check_atx_agent_version
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\init.py", line 311, in check_atx_agent_version
    version = requests.get("http://127.0.0.1:%d/version" % port).text.strip()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by Clark3333** [comment]
又卡在扫货了，大佬求教
**C:\Users\User\Desktop\JGM-Automator-master>python main.py
2019-11-06 02:34:45,064 - root - INFO - device screen size 960, 540
2019-11-06 02:34:45,079 - root - INFO - App is front. JGM agent start in 5 seconds
2019-11-06 02:34:52,208 - root - INFO - [Wed Nov  6 02:34:52 2019] Task finished.    ++++++
2019-11-06 02:34:54,120 - root - INFO - [Wed Nov  6 02:34:54 2019] Train come.
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    instance.start()
  File "C:\Users\User\Desktop\JGM-Automator-master\automator.py", line 46, in start
    self.check_goods()
  File "C:\Users\User\Desktop\JGM-Automator-master\automator.py", line 167, in check_goods
    self.harvest(self.harvest_filter, good_id)
  File "C:\Users\User\Desktop\JGM-Automator-master\automator.py", line 85, in harvest
    pos_id = self.guess_good(good)
  File "C:\Users\User\Desktop\JGM-Automator-master\automator.py", line 97, in guess_good
    diff_screens = self.get_screenshot_while_touching(GOODS_POSITIONS[good_id])
  File "C:\Users\User\Desktop\JGM-Automator-master\automator.py", line 108, in get_screenshot_while_touching
    self.d.touch.down(x,y)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\session.py", line 349, in down
    obj.jsonrpc.injectInputEvent(ACTION_DOWN, x, y, 0)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 440, in __call__
    params, http_timeout)
  File "<C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\decorator.py:decorator-gen-12>", line 2, in jsonrpc_retry_call
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\retry\api.py", line 74, in retry_decorator
    logger)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 457, in jsonrpc_retry_call
    return self.jsonrpc_call(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\uiautomator2\__init__.py", line 542, in jsonrpc_call
    raise err
uiautomator2.exceptions.JsonRpcError: -32601 Method not found: <Method not found> data: , method: injectInputEvent**
