### ISSUE TITLE
执行screenshot的时候opencv报错

### ISSUE THREAD

**Issue by Dongagent** [Jiahonzheng/JGM-Automator#9]
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    instance.start()
  File "/Users/y.dongdong/Downloads/DongHub/JGM-Automator/automator.py", line 44, in start
    self._match_target(target)
  File "/Users/y.dongdong/Downloads/DongHub/JGM-Automator/automator.py", line 116, in _match_target
    screen = self.d.screenshot(format="opencv")
  File "/anaconda3/lib/python3.7/site-packages/uiautomator2/__init__.py", line 1186, in screenshot
    return self.session().screenshot(*args, **kwargs)
  File "</anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-6>", line 2, in screenshot
  File "/anaconda3/lib/python3.7/site-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/anaconda3/lib/python3.7/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/anaconda3/lib/python3.7/site-packages/uiautomator2/session.py", line 469, in screenshot
    r = requests.get(self.server.screenshot_uri, timeout=10)
  File "/anaconda3/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/anaconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/anaconda3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/anaconda3/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/anaconda3/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/anaconda3/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/anaconda3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)

我尝试了下增加import cv2，发现不是这个问题，所以行号可能跟源文件差1行，想问下你的版本号可以发一下不？

**Comment by TsingWei** [comment]
抱歉这么晚才看到你的问题,你先拉最新版本试试
